# Generated by Django 6.0.6 on 2026-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obraarte',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='obraarte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras/'),
        ),
    ]
